API/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()

router.register(r'dataElements', DataElementViewSet)
router.register(r'pointDataElements', PointViewSet)
# router.register(r'^pointDataElements/(?P<id>.+)/$', PointViewSet.as_view())
router.register(r'polygonDataElements', PolygonViewSet)
router.register(r'multiPolygonDataElements', MultiPolygonViewSet)
router.register(r'lineStringDataElements', LineStringViewSet)
router.register(r'multiLineStringDataElements', MultiLineStringViewSet)
router.register(r'makaneyyat', MakaneyyaViewSet)
# router.register(r'search', DataElementSearchViewSet, base_name="DataElement-search")
router.register(r'dataElementsMerge', DataElementMergeViewSet, base_name="DataElement-Merge")
router.register(r'categories', CategoriesListViewSet, base_name="Categories-List")

urlpatterns = [
    url(r'^', include(router.urls)),
]

Map/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from .views import *

app_name = 'map'
urlpatterns = [
	url(r'import/shpFile', importShpFile , name = 'shpFile-import'),
	url(r'update/index', update_index , name = 'update-index'),
	url(r'rebuild/index',rebuild_index,name='rebuild-index'),
	url(r'import/jsonFile', importJsonFile , name = 'jsonFile-import'),
	url(r'makaneyya/explore', MakaneyyaListView.as_view(), name = 'makaneyya-list'),
	url(r'makaneyya/view', MakaneyyaMapView.as_view()),
	url(r'makaneyya/create', DataElementExploreView.as_view(), name='makaneyya-create'),
	url(r'makaneyya/(?P<pk>[0-9]+)/delete/$', MakaneyyaDelete.as_view(), name='makaneyya-delete'),
	url(r'makaneyya/search', ExploreGBIFView.as_view(), name = 'gbif-search'),
	url(r'', index, name = "home"),
]

website/models.py
from django.db import models

# New imports added for ParentalKey, Orderable, InlinePanel, ImageChooserPanel

from modelcluster.fields import ParentalKey

from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, InlinePanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsearch import index

from .utilities import TranslatedField



class HomePage(Page):

	def get_context(self, request):
		context = super(HomePage, self).get_context(request)
		sitepages = self.get_children().live()
		context["sitepages"] = sitepages
		return context

	title_ar = models.CharField(max_length=250, blank = True)
	body_en = RichTextField(blank = True)
	body_ar = RichTextField(blank = True)
	body = TranslatedField('body_en', 'body_ar')
	Title = TranslatedField('title', 'title_ar')
	
	content_panels = Page.content_panels + [FieldPanel('body_en', classname = 'full'),
	FieldPanel('body_ar', classname = 'full'), FieldPanel('title_ar'),]


class SitePage(Page):

	title_ar = models.CharField(max_length=250, blank = True)
	body_en = RichTextField(blank = True)
	body_ar = RichTextField(blank = True)
	intro_en = models.CharField(max_length = 250, blank = True )
	intro_ar = models.CharField(max_length = 250, blank = True )
	body = TranslatedField('body_en', 'body_ar')
	Title = TranslatedField('title', 'title_ar')
	intro = TranslatedField('intro_en', 'intro_ar')
	
	content_panels = Page.content_panels + [
		FieldPanel('intro_en'),
		FieldPanel('body_en', classname = 'full'),
		FieldPanel('title_ar'),
		FieldPanel('intro_ar'),
		FieldPanel('body_ar', classname = 'full'),
		InlinePanel('gallery_images', label="Gallery images"),
	]



class SitePageGalleryImage(Orderable):
    page = ParentalKey(SitePage, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)
    
    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]

website/views.py
from django.shortcuts import render

# Create your views here.

website/templates/components/footer.html
{% load custom %}
{% load wagtailcore_tags %}
<footer>
    <nav class="navbar">
      <div class="container-fluid">
      <div class="navbar-header">
        <a href="#" class="brand-logo"><img id="logo" src="https://res.cloudinary.com/sockhat-dev/image/upload/v1491988583/logo_grey_zldy5b.svg"></a>
      </div>
        {% get_site_root as site_root %}
        {% navbar parent=site_root calling_page=self %}
      </div>
    </nav>  
</footer>

website/templates/components/header.html
{% load custom %}
{% load wagtailcore_tags %}
{% get_alt_lang request.LANGUAGE_CODE as alt_lang %}
{% get_text_dir request.LANGUAGE_CODE as txt_dir %}
<header>
	<nav class="navbar">
		<div class="container-fluid">

      <div class="navbar-header">

        <a class="navbar-brand" href="//{{ request.get_host }}"><img id="main-logo" src='https://res.cloudinary.com/faradthakh/image/upload/v1520446138/logo.png' alt='Makaneyyat'></a>
        <a href="../{{alt_lang}}" class="btn btn-default navbar-btn">{{alt_lang}}</a>
      </div>
  		{% get_site_root as site_root %}
  		{% navbar parent=site_root calling_page=self %}
         {% if user.is_authenticated %}
                <a class="btn btn-success navbar-btn btn-olive explore" href="{% url 'logout'%}">Logout</a>

                {% else %}

                <a class="btn btn-success navbar-btn btn-olive explore" href="{% url 'login'%}?next={{request.path}}">Login</a>

                <a class="btn btn-success navbar-btn btn-olive explore" href="{% url 'signup'%}">Sign Up</a>

         {% endif %}
            <a class="btn btn-success navbar-btn btn-olive explore" href="{% url 'map:gbif-search' %}">Explore!</a>
        {% if user.is_authenticated %}
               <a class="btn btn-success navbar-btn btn-olive" href="{% url 'map:makaneyya-list' %}">Create Makaneyya!</a>
         {% endif %}


		</div>    
	</nav>

  <div id="tooltip" data-toggle="tooltip" title="Photographic collage of 1918 World War I archival image of Ṣarīda area of Wadi Dayr Ballū t (black and white background image) with photograph of same vantage point in winter 2017 (color foreground image)."‏>
     <span class="glyphicon glyphicon-info-sign"></span>
  </div>
</header>