API/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

router = routers.DefaultRouter()

router.register(r'dataElements', DataElementViewSet)
router.register(r'pointDataElements', PointViewSet)
# router.register(r'^pointDataElements/(?P<id>.+)/$', PointViewSet.as_view())
router.register(r'polygonDataElements', PolygonViewSet)
router.register(r'multiPolygonDataElements', MultiPolygonViewSet)
router.register(r'lineStringDataElements', LineStringViewSet)
router.register(r'multiLineStringDataElements', MultiLineStringViewSet)
router.register(r'makaneyyat', MakaneyyaViewSet)
# router.register(r'search', DataElementSearchViewSet, base_name="DataElement-search")
router.register(r'dataElementsMerge', DataElementMergeViewSet, base_name="DataElement-Merge")
router.register(r'categories', CategoriesListViewSet, base_name="Categories-List")

urlpatterns = [
    url(r'^', include(router.urls)),
]

Map/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from .views import *

app_name = 'map'
urlpatterns = [
	url(r'import/shpFile', importShpFile , name = 'shpFile-import'),
	url(r'update/index', update_index , name = 'update-index'),
	url(r'rebuild/index',rebuild_index,name='rebuild-index'),
	url(r'import/jsonFile', importJsonFile , name = 'jsonFile-import'),
	url(r'makaneyya/explore', MakaneyyaListView.as_view(), name = 'makaneyya-list'),
	url(r'makaneyya/view', MakaneyyaMapView.as_view()),
	url(r'makaneyya/create', DataElementExploreView.as_view(), name='makaneyya-create'),
	url(r'makaneyya/(?P<pk>[0-9]+)/delete/$', MakaneyyaDelete.as_view(), name='makaneyya-delete'),
	url(r'makaneyya/search', ExploreGBIFView.as_view(), name = 'gbif-search'),
	url(r'', index, name = "home"),
]

Map/models.py
from django.contrib.gis.db import models
from django.contrib.gis import geos
from django.contrib.postgres.fields import JSONField
from django.conf import settings
from django.utils import timezone
from taggit.managers import TaggableManager

class Source(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=2000, null=False, blank=False)

    def __str__(self):
        return str(self.title)    
    
class Subject(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=2000, null=False, blank=False)
    
    def __str__(self):
        return str(self.title)

class Year(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return str(self.title)

class CLCLevel1(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return str(self.title)

class CLCLevel2(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return str(self.title)

class CLCLevel3(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return str(self.title)

class CLCLevel4(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return str(self.title)    

# Create your models here.
class CORINELandCover(models.Model):
    id = models.IntegerField(primary_key = True)
    level1 = models.CharField(max_length = 100)
    level2 = models.CharField(max_length = 100)
    level3 = models.CharField(max_length = 100)
    level4 = models.CharField(max_length = 100, null=True, blank=True)

    def __str__(self):
        return str(self.id)


class DataElement(models.Model):

    title = models.CharField(max_length=500, null=True, blank=True)
    subject = models.CharField(max_length=500, null=True, blank=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    creator =models.CharField(max_length=500, null=True, blank=True)
    publisher = models.CharField(max_length=500, null=True, blank=True)
    contributor = models.CharField(max_length=500, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    type = models.CharField(max_length=500, null=True, blank=True)
    format = models.CharField(max_length=500, null=True, blank=True)
    source = models.CharField(max_length=500, null=True, blank=True)
    language = models.CharField(max_length=500, null=True, blank=True)
    coverage = models.CharField(max_length=500, null=True, blank=True)
    rights = models.CharField(max_length=500, null=True, blank=True)
    relation = models.CharField(max_length=500, null=True, blank=True)
    identifier = models.CharField(max_length=500, null=True, blank=True)

    ar_title = models.CharField(max_length=500, null=True, blank=True)
    ar_subject = models.CharField(max_length=500, null=True, blank=True)
    ar_description = models.CharField(max_length=500, null=True, blank=True)

    ar_publisher = models.CharField(max_length=500, null=True, blank=True)
    ar_creator = models.CharField(max_length=500, null=True, blank=True)
    ar_contributor = models.CharField(max_length=500, null=True, blank=True)
    ar_format = models.CharField(max_length=500, null=True, blank=True)
    ar_relation = models.CharField(max_length=500, null=True, blank=True)
    ar_type = models.CharField(max_length=500, null=True, blank=True)
    ar_coverage = models.CharField(max_length=500, null=True, blank=True)


    ar_source = models.CharField(max_length=500, null=True, blank=True)
    ar_rights = models.CharField(max_length=500, null=True, blank=True)

    clc = models.ForeignKey(CORINELandCover, on_delete = models.CASCADE, null=True, blank=True) 
    clc_level1 = models.ForeignKey(CLCLevel1, on_delete = models.CASCADE, null=True, blank=True)
    clc_level2 = models.ForeignKey(CLCLevel2, on_delete = models.CASCADE, null=True, blank=True)
    clc_level3 = models.ForeignKey(CLCLevel3, on_delete = models.CASCADE, null=True, blank=True)
    clc_level4 = models.ForeignKey(CLCLevel4, on_delete = models.CASCADE, null=True, blank=True)

    source_id = models.ForeignKey(Source, on_delete = models.CASCADE, null=True, blank=True)
    subject_id = models.ForeignKey(Subject, on_delete = models.CASCADE, null=True, blank=True)
    year = models.ForeignKey(Year, on_delete = models.CASCADE, null=True, blank=True)
    
    properties = JSONField(null=True, blank=True)

    # @property
    # def identifier(self):
    #     return self.id

    @property
    def related(self):
        """this proprty represent all related dataelements e.i. dataelements
        which exist in the same makaneyya"""
        return []

    def __str__(self):
        return str(self.id)



class PointDataElement(DataElement):
    geometry = models.PointField()

    @property
    def related(self):
        """this proprty represent all related dataelements e.i. dataelements
        which exist in the same makaneyya"""
        return []

    def __str__(self):
        return str(self.id)

class PolygonDataElement(DataElement):
    geometry = models.PolygonField()
    @property
    def related(self):
        """this proprty represent all related dataelements e.i. dataelements
        which exist in the same makaneyya"""
        return []

    def __str__(self):
        return str(self.id)

class MultiPolygonDataElement(DataElement):
    geometry = models.MultiPolygonField()

    @property
    def related(self):
        """this proprty represent all related dataelements e.i. dataelements
        which exist in the same makaneyya"""
        return []

    def __str__(self):
        return str(self.id)

class LineStringDataElement(DataElement):
    geometry= models.LineStringField()

    @property
    def related(self):
        """this proprty represent all related dataelements e.i. dataelements
        which exist in the same makaneyya"""
        return []

    def __str__(self):
        return str(self.id)

class MultiLineStringDataElement(DataElement):
    geometry = models.MultiLineStringField()
    
    @property
    def related(self):
        """this proprty represent all related dataelements e.i. dataelements
        which exist in the same makaneyya"""
        return []

    def __str__(self):
        return str(self.id)

class Makaneyya(models.Model):
    description = models.TextField(max_length = 1000,blank = True)
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='makaneyyatCreated',default=1)
    date = models.DateTimeField(default=timezone.now)
    lastEdited = models.DateTimeField(auto_now = True)
    approved = models.BooleanField(default=False)
    lon = models.FloatField('longitude', null=True, blank=True, default=32.223516)
    lat = models.FloatField('latitude', null=True, blank=True, default=35.239109)
    tags = TaggableManager(blank = True);
    gbifQuery = models.CharField(max_length=100000,blank = True,default='');
    gbifQueryByArea = models.CharField(max_length=500,blank = True,default='');
    isGBIFMakanyyea = models.BooleanField(default=False)

    elements = models.ManyToManyField(DataElement, blank=True, related_name='makaneyyat')
    point_elements = models.ManyToManyField(PointDataElement,blank=True, related_name='makaneyyat2')
    line_elements = models.ManyToManyField(LineStringDataElement,blank=True, related_name='makaneyyat3')
    multi_line_elements = models.ManyToManyField(MultiLineStringDataElement,blank=True, related_name='makaneyyat4')
    polygon_elements = models.ManyToManyField(PolygonDataElement,blank=True, related_name='makaneyyat5')
    multi_polygon_elements = models.ManyToManyField(MultiPolygonDataElement,blank=True, related_name='makaneyyat6')

    @property
    def related(self):
        """this proprty represent all related dataelements e.i. dataelements
        which exist in the same makaneyya"""
        return []

    def __str__(self):
        return str(self.id)

Map/forms.py
from django import forms
from import_export.forms import ImportForm, ConfirmImportForm


class ImportShpFileForm(forms.Form):

	shpfile = forms.FileField(label = 'Select a .shp File ', required = True)
	shxfile = forms.FileField(label = 'Select a .shx File ', required = True)
	prjfile = forms.FileField(label = 'Select a .prj File ' , required = True)
	dbffile = forms.FileField(label = 'Select a .dbf File ', required = True)
	qpjfile = forms.FileField(label = 'Select a .qpj File ', required = True)

class ImportJsonFileForm(forms.Form):
	jsonfile = forms.FileField(label = 'Select a .geojson File ', required = True)
	createmakaneyya = forms.BooleanField(label='Do you want to create makaneyya?', required = False)

class DataElementImportForm(ImportForm):
	is_gbif = forms.BooleanField(label='Include GBIF data?', required = False)

Map/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User
from .models import *
from .forms import ImportShpFileForm,ImportJsonFileForm
from .load import loadShpFile
from .load import loadJsonFile
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.csrf import csrf_exempt
from Makaneyyat.utils import *
from haystack.management.commands.update_index import Command as UpdateCommand
from haystack.management.commands.rebuild_index import Command as RebuildCommand
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def index(request):
	return render(request, 'Map/makaneyya_view.html') 

class MakaneyyaDelete(generic.DeleteView):
    model = Makaneyya
    success_url = reverse_lazy('makaneyya-list')

@staff_member_required
def importShpFile(request, **kwargs):
    if(request.method == 'POST'):
        form = ImportShpFileForm(request.POST, request.FILES)
        if form.is_valid():
            #setting the file name 
            file_name = str(datetime.now().replace(microsecond = 0))
           
            #saving the shp file into the data/shpFiles dir 
            saveMemoryFile(file = request.FILES['shpfile'] , file_name = file_name )
            saveMemoryFile(file = request.FILES['shxfile'] , file_name = file_name , extension = 'shx' )
            saveMemoryFile(file = request.FILES['dbffile'] , file_name = file_name , extension = 'dbf' )
            saveMemoryFile(file = request.FILES['qpjfile'] , file_name = file_name , extension = 'qpj' )
            saveMemoryFile(file = request.FILES['prjfile'] , file_name = file_name , extension = 'prj' )
            
            loadShpFile(file_name, request.user.username)
            return render(request , 'Map/importShpFile.html' , {'form': ImportShpFileForm() , 'submition' : True})
        else:
            return render(request, 'Map/importShpFile.html', {'form': form, 'submition' : False, 'errors' : form.errors})
    else :
        form = ImportShpFileForm()
        return render(request , 'Map/importShpFile.html' , {'form': form})

@staff_member_required
def update_index(request,**kwargs):
    try:
        UpdateCommand().handle()
        messages.success(request,'Update Index Done')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except:
        messages.error(request, 'Error in updating index')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def rebuild_index(request):
    try:
        RebuildCommand().handle(interactive=False,batchsize=1000,workers=12)
        messages.success(request, 'Rebuild Index Done')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except:
        messages.error(request, 'Failed to rebuild index')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



@staff_member_required
def importJsonFile(request, **kwargs):
    if (request.method == 'POST'):
        form = ImportJsonFileForm(request.POST, request.FILES)
        if form.is_valid():
            # setting the file name
            file_name = str(datetime.now().replace(microsecond=0))
            saveMemoryFile(file=request.FILES['jsonfile'], file_name=file_name , extension = 'geojson')
            createMakaneyya = form.cleaned_data['createmakaneyya']

            print(str(request.FILES['jsonfile'].name) + ' ' + file_name)
            if createMakaneyya:
                kwagrs = {'title': str(request.FILES['jsonfile'].name) + ' ' + file_name,
                          'author': User.objects.get(id=request.user.id),
                          'isGBIFMakanyyea': False}

                makaneyya = Makaneyya.objects.create(**kwagrs)

                loadJsonFile(file_name, request.user,makaneyya=makaneyya)
            else:
                loadJsonFile(file_name, request.user)
            return render(request, 'Map/importJsonFile.html', {'form': ImportJsonFileForm(), 'submition': True})
        else:
            return render(request, 'Map/importJsonFile.html', {'form': form, 'submition': False, 'errors': form.errors})
    else:
        form = ImportJsonFileForm()
        return render(request, 'Map/importJsonFile.html', {'form': form})

class MakaneyyaListView(LoginRequiredMixin,generic.ListView):
    template_name = 'Map/makaneyyat_list.html'
    context_object_name = 'makaneyyat'
    login_url = '/accounts/login/?next='

    def get_queryset(self):
        result =  Makaneyya.objects.filter(approved=True)
        if self.request.GET.get("author"):
            result = result.filter(author__username__icontains = self.request.GET.get("author"))
        if self.request.GET.get("title"):
            result = result.filter(title__icontains = self.request.GET.get("title"))
        if self.request.GET.getlist("tags"):
            result = result.filter(tags__name__in = self.request.GET.getlist("tags"))
        return result

class DataElementExploreView(generic.TemplateView):
    template_name = 'Map/makaneyya_edit.html'

class MakaneyyaMapView(generic.TemplateView):
    template_name = 'Map/makaneyya_view.html'


class ExploreGBIFView(generic.TemplateView):
    template_name = 'Map/explore_gbif.html'

Map/templates/Map/base.html
{% load static %}
{% load map_temptags %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    {# Global stylesheets #}
    <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css"
          type="text/css">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.0/ol.css" type="text/css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Map/css/map.css' %}" type="text/css">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">#}
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.0/ol.js"></script> -->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}
    {% endblock %}
</head>
<body class="{% block body_class %}{% endblock %}">

{% block content %}
    {% include 'Map/header.html' %}
    <div class="row">

        <div id="left-panel" class="col-md-2" style="">
            {% block left-panel %}{% endblock %}</div>
        <div class="loading-mask loader">
            <img class="load-image" src='{% static "Map/img/giphy.gif" %}'/>
        </div>
        <div id="mid-panel" class="col-md-12">{% block mid-panel %}{% endblock %}</div>
        <div id="right-panel" class="col-md-2" >{% block right-panel %}{% endblock %}</div>
    </div>

    {% block bottom-panel %}
         <div class="row justify-content-center">
                <div id='page-nav'></div>
            </div>
        <div class="row">
        <div class="col">

         <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#makaneyyat">Makaneyyat</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#gpif">GBIF data tool</a>
                </li>
         </ul>
        </div>
            <div class="col">
                <button class="btn btn-olive" id="btn-lang" onclick="change_lang()">A-ع</button>
                <span class="counter" id="counter">0</span>
            </div>

        </div>
        <div class="row">

            <div class="col table-responsive">
                <div class="tab-content">
                    <div id="makaneyyat" class="tab-pane active"><br>
                        <table class="table table-striped table-sm table-hover" id="info-table">
                            <tbody id='info-table-body'>
                            </tbody>
                        </table>
                    </div>
                    <div id="gpif" class="tab-pane fade"><br/>
                        <table class="table table-striped table-sm table-hover" id="gpif-table">
                            <tbody id='gpif-table-body'>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

    {% include 'Map/footer.html' %}
{% endblock %}

{# Global javascript #}
<script>
    {%get_base_api_url as api_url%}
    var base_api_url = "{{api_url}}";
</script>
<script src='{% static "Map/js/map.js" %}'></script>
<link rel="stylesheet" href="{% static 'Map/css/postLoad.css' %}" type="text/css">
{% block extra_js %}
    {# Override this in templates to add extra javascript #}
{% endblock %}
</body>
</html>

Map/templates/Map/explore_gbif.html
{% extends 'Map/base.html' %}
{% load map_temptags %}
{% load static %}
{% block extra_css %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
{% endblock %}
{% block body_class %}container-fluid{% endblock %}

{% block left-panel %}
    <div id="map-facets">
    </div>
{% endblock %}

{% block mid-panel %}
    <div id="map" class="map">
    </div>
    <div id='popup' class="ol-popup">
        <a href="#" id="popup-closer" class="ol-popup-closer"></a>
        <div id="popup-content">
            <div class="search-box">
                <h5>Polygon info:</h5>
                <p>Level1, Level2, level 3, level4 Year: <span id="year-search1"></span></p>
                <h5>Get GBIF Plantae Families</h5>
                <div class="multiselect">
                    <div class="selectBox" onclick="showCheckboxes()">
                        <select>
                            <option value="all_families">Select Families</option>
                        </select>
                        <div class="overSelect"></div>
                    </div>
                    <div id="checkboxes" style="height: 80px;">

                    </div>
                </div>
                <div id="families-box">

                </div>
                <h5>Get GBIF Occurrence by year</h5>
                <div class="multiselect">
                    <div class="selectBox" onclick="showCheckboxesYears()">
                        <select>
                            <option value="all_years">Select Years</option>
                        </select>
                        <div class="overSelect"></div>
                    </div>
                    <div id="checkboxes-years" style="height: 80px;">

                    </div>
                </div>
                <button id="search-box-filter">Search</button>
                <button id="clear-points">Clear</button>
            </div>
            <div class="no-data-result">
                <p>No GBIF data in this Polygon!</p>
            </div>
        </div>
        <div id="loader">
            <img class="load-image" src='{% static "Map/img/giphy.gif" %}'/>
        </div>
    </div>
{% endblock %}

{% block right-panel %}
    <div id="map-options" class='map-options'>
        <p>Basemap:</p>
        <select class="custom-select" id="select-base-map" onchange="reload_tile_layer()">
            <option value="Stamen">Stamen Map</option>
            <option value="OSM">Open Street Map</option>
            <option value="Bing">Bing Map</option>
        </select>
        <p>Display:</p>
        <select class="custom-select" id="select-display-text" onchange="update_display_text()">
            <option value="title">title</option>
            <option value="level1">Level 1</option>
            <option value="level2">Level 2</option>
            <option value="level3">Level 3</option>
            <option value="level4">Level 4</option>
        </select>
        <br>
        <label class="gbif-data"> GBIF data tool </label>
        <div class="search">
            <input type="text" id="search" name="search"/>
            <div class="autocomplete">
            </div>
            <p class="search-button" id="search-btn">Search</p>
            <hr/>
            <p class="search-area-button search-button" id="search-by-area-btn">Draw Polygon</p>
            <br/>

            <label class="search-label">Amount of result</label>
            <br/>
            <input type="text" id="query-num" name="query-num"/>
            <label class="search-label">Country</label>
            <br/>
            <select id="country">
                <option value="">All</option>
                <option value="PS">Palestine</option>
            </select>
        </div>
        <div id="geometry-name" >
            <p class="value"></p>
        </div>

    </div>
{% endblock %}

{% block extra_js %}
    <script src='{% static "Map/js/makaneyyaEditor.js" %}'></script>
    <script src='{% static "Map/js/explore_gbif.js" %}'></script>
    <script src='{% static "Map/js/polygon_search_box.js" %}'></script>

{% endblock %}

Map/templates/Map/footer.html
<footer>
  <a href="#"><img class="logo" src="https://res.cloudinary.com/sockhat-dev/image/upload/v1491988583/logo_grey_zldy5b.svg" alt="main logo"></a>
</footer>

Map/templates/Map/header.html
{% load custom %}
{% load wagtailcore_tags %}
{% get_alt_lang request.LANGUAGE_CODE as alt_lang %}
{% get_text_dir request.LANGUAGE_CODE as txt_dir %}
<header>
	<div class="row">
		<div class="col-2">
			<a href="/"><img class="nav-logo" src="https://res.cloudinary.com/sockhat-dev/image/upload/v1491988583/logo_green_k8u53n.svg" alt="main logo">
			</a>
		</div>
          		{% get_site_root as site_root %}

		<div class="col-10">{%include 'registration/header.html'%}</div>
	</div>
</header>

Map/templates/Map/makaneyyat_list.html
{% load static %}
{% load map_temptags %}
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="{%static 'Map/css/makaneyyat-list.css' %}" type="text/css">
  </head>
  <body>

    {%include 'registration/header.html'%}
    <header></header>
    <div class="container">
      <form  method="GET" id="makaneyyat-filter-form">
        <span id='makaneyyat-filter-field'>Author: <input type="text" name="author" placeholder="filter author name"></span>
        <span id='makaneyyat-filter-field'>Title: <input type="text" name="title" placeholder="filter by title"></span>
        <span id='makaneyyat-filter-field'>Tags: <input type="text" name="tags" placeholder="filter by rags"></span>
        <input type="submit" name="submit" value="Filter">
      </form>
    </div>
  <div class="container">
   <div class="card makaneyya-card">
      <img class="card-img-top" src="https://res.cloudinary.com/faradthakh/image/upload/v1521376793/makaneyya-item-bg.png" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Create Makaneyya</h5>
        <p class="card-text">Create Makaneyyat and explore all our elements!</p>
        <a href="{% url 'map:makaneyya-create' %}" class="btn btn-primary">Go</a>
      </div>
    </div>
    {%for makaneyya in makaneyyat%}
    <div class="card makaneyya-card">
      <img class="card-img-top" src="https://res.cloudinary.com/faradthakh/image/upload/v1521376793/makaneyya-item-bg.png" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">{{makaneyya.title}}</h5>
        <p class="card-text">{{makaneyya.description}}</p>
        <a href="view/{{makaneyya.id}}" class="btn btn-primary">Display</a>
      </div>
    </div>
    {%empty%}
      <p> No matchiing makaneyyat found!</p>
    {%endfor%}
  </div>
  <footer>
     <div class="container-fluid">
        <a href="//{{ request.get_host }}"><img width="170px" src="https://res.cloudinary.com/sockhat-dev/image/upload/v1491988583/logo_grey_zldy5b.svg"></a>
    </div>
  </footer>
  <script type="text/javascript" src="{% static 'Map/js/makaneyyatList.js' %}"></script>
  </body>
</html>